public enum EventDefine
{

    //网络交互事件标识
    Login,
    Register,
    ChangePassword,
    CreateHero,
    GetHeroInfo,
    GetHeroListInfo,
    SaveHeroInfo,
    UpdateHeroList,
    /////////////////////////////////////////
    //UI事件标识
    Message,
    //给格子赋值
    UI_SetBagInfo,
    //拿到背包信息
    UI_SendBagInfo,
    //开始游戏初始化背包
    InitBag,
    //Sned,
    Test_GetImage,
    //设置英雄信息
    UI_SetHeroInfo,
    //C层发送背包信息
    UI_SetInventoryC,
    //C层发送玩家信息到背包界面
    UI_SetPlayerInfo2InvenC,
    //C层发送玩家信息到背包界面
    UI_SetPlayerInfo2Inven,
    //给装备栏赋值
    UI_SetEquipInfo,
    //拿到装备栏信息
    UI_SendEquipInfo,
    //开始游戏初始化装备
    InitEquip,
    //开始游戏初始化装备C
    InitEquipC,
    //UI发送装备信息到系统
    UI_SendEquipInfoV,
    //UI
    //**************************
    //设置npc状态
    ChangeNpcState,
    //展示对话
    ShowTalkText,
    ShowTalkTextC,
    //展示task面板的button
    ShowTaskButton,
    ShowTaskButtonC,
    Init,
    //展示TaksUI面板
    ShowUI,
    ShowUIC,
    //设置当前npc
    SetCurrentNpc,
    SetCurrentNpcNull,
    //激活task面板
    SetTaskPanel,
    SetTaskPanelC,
    //对话结束时展示任务面板
    SetTaskPanelEndTalk,
    //改变任务进度
    ChangeDialogueTask,
    ChangeOtherTask,
    //展示小任务面板进度
    MiniTaskShow,
    MiniTaskShowC,
    //完成任务
    FinishTaskDelete,
    FinishTaskGet,
    //第一次检查任务
    FirstCheck,
    //Test
    Test,
    ////////////////////////////////////
    //玩家系统交互事件
    GetDamage,
    Player_GetPlayerInfo
}
