public enum EventDefine
{

    //网络交互事件标识
    Login,
    Register,
    ChangePassword,
    CreateHero,
    GetHeroInfo,
    GetHeroListInfo,
    SaveHeroInfo,
    UpdateHeroList,
    /////////////////////////////////////////
    //UI事件标识
    Message,
    //给格子赋值
    UI_SetBagInfo,
    //拿到背包信息
    UI_SendBagInfo,
    //开始游戏初始化背包
    InitBag,
    //Sned,
    Test_GetImage,

    //**************************
    //设置npc状态
    ChangeNpcState,
    //展示对话
    ShowTalkText,
    ShowTalkTextC,
    //展示task面板的button
    ShowTaskButton,
    ShowTaskButtonC,
    Init,
    //展示TaksUI面板
    ShowUI,
    ShowUIC,
    //设置当前npc
    SetCurrentNpc,
    SetCurrentNpcNull,
    //激活task面板
    SetTaskPanel,
    SetTaskPanelC,
    //对话结束时展示任务面板
    SetTaskPanelEndTalk,
    //改变任务进度
    ChangeDialogueTask,
    ChangeOtherTask,
    //展示小任务面板进度
    MiniTaskShow,
    MiniTaskShowC,
    //Test
    Test,
    ////////////////////////////////////
}
